### ISSUE TITLE
Issue while running app

### ISSUE THREAD

**Issue by ajaythukral** [studerw/td-ameritrade-java-client-demo#7]
After doing maven build and setting application properties file, I am getting following error while starting app. Any pointer to fix the same.
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springDocConfig' defined in URL [jar:file:/D:/samplecode/td-ameritrade-java-client-demo-master/target/td-ameritrade-java-client-demo-1.0.0.jar!/BOOT-INF/classes!/com/studerw/tda/demo/config/SpringDocConfig.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.studerw.tda.demo.config.SpringDocConfig$$EnhancerBySpringCGLIB$$7e28adab]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Required key 'api.prefix' not found

**Comment by studerw** [comment]
The issue (probably) is related to the TdaController has a `@RequestMapping("${api.prefix}/tda")`. That means it expects some Spring property of "api.prefix" defined. By default in that project, the application.properties file under src/main/resources does define that property. 

My guess is that you're trying to run this app in some IDE or some other way, and you haven't set up the class path correctly to include `src/main/resources` (which Maven does by default in most cases if you run on command line). 

So I'd need more info on how you're trying to run this app and if you've modified or removed the application.properties file.

One way to test the app out on the command line is to run `mvn spring-boot:run`. If you do that, do you get a similar error?

**Comment by ajaythukral** [comment]
First of all, thanks William for this repository.  It helped me a lot.
I tried using eclipse IDE and I was getting same error. Now I am building it through command prompt only

My java version is java 16 and maven is 3.8.2. While running below command mvn spring-boot:run. I am getting this error


D:\samplecode\td-ameritrade-java-client-demo-master>mvn spring-boot:run
[INFO] Scanning for projects...
[INFO]
[INFO] -----------< com.studerw.tda:td-ameritrade-java-client-demo >-----------
[INFO] Building td-ameritrade-java-client-demo 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.4.0:run (default-cli) > test-compile @ td-ameritrade-java-client-demo >>>
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-rules) @ td-ameritrade-java-client-demo ---
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ td-ameritrade-java-client-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 0 resource
[INFO] Copying 30 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ td-ameritrade-java-client-demo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 12 source files to D:\samplecode\td-ameritrade-java-client-demo-master\target\classes
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ td-ameritrade-java-client-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ td-ameritrade-java-client-demo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to D:\samplecode\td-ameritrade-java-client-demo-master\target\test-classes
[INFO]
[INFO] <<< spring-boot-maven-plugin:2.4.0:run (default-cli) < test-compile @ td-ameritrade-java-client-demo <<<
[INFO]
[INFO]
[INFO] --- spring-boot-maven-plugin:2.4.0:run (default-cli) @ td-ameritrade-java-client-demo ---
[INFO] Attaching agents: []
{spring.web.resources.chain.cache=false, spring.web.resources.cache.period=0}

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.0)

2021-08-25 01:36:44.195  INFO 21272 --- [  restartedMain] com.studerw.tda.demo.WebApp              : Starting WebApp using Java 16.0.2 on DESKTOP-B7OGPA2 with PID 21272 (D:\samplecode\td-ameritrade-java-client-demo-master\target\classes started by shvid in D:\samplecode\td-ameritrade-java-client-demo-master)
2021-08-25 01:36:44.198  INFO 21272 --- [  restartedMain] com.studerw.tda.demo.WebApp              : No active profile set, falling back to default profiles: default
2021-08-25 01:36:44.256  INFO 21272 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2021-08-25 01:36:44.256  INFO 21272 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2021-08-25 01:36:45.455  INFO 21272 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-08-25 01:36:45.466  INFO 21272 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-08-25 01:36:45.467  INFO 21272 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.39]
2021-08-25 01:36:45.564  INFO 21272 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-08-25 01:36:45.564  INFO 21272 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1305 ms
2021-08-25 01:36:45.719  INFO 21272 --- [  restartedMain] c.s.tda.demo.config.ControllerSetup      : creating ControllerSetup -- should only see me once.
2021-08-25 01:36:45.720  INFO 21272 --- [  restartedMain] c.s.tda.demo.config.SpringDocConfig      : Instantiating SwaggerConfig - should only see me once
2021-08-25 01:36:45.723  WARN 21272 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springDocConfig' defined in file [D:\samplecode\td-ameritrade-java-client-demo-master\target\classes\com\studerw\tda\demo\config\SpringDocConfig.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.studerw.tda.demo.config.SpringDocConfig$$EnhancerBySpringCGLIB$$6e58deb6]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Required key 'api.prefix' not found
2021-08-25 01:36:45.732  INFO 21272 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-08-25 01:36:45.750  INFO 21272 --- [  restartedMain] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-08-25 01:36:45.771 ERROR 21272 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springDocConfig' defined in file [D:\samplecode\td-ameritrade-java-client-demo-master\target\classes\com\studerw\tda\demo\config\SpringDocConfig.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.studerw.tda.demo.config.SpringDocConfig$$EnhancerBySpringCGLIB$$6e58deb6]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Required key 'api.prefix' not found
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:314) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:295) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1356) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1206) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925) ~[spring-context-5.3.1.jar:5.3.1]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.1.jar:5.3.1]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-2.4.0.jar:2.4.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-2.4.0.jar:2.4.0]
        at com.studerw.tda.demo.WebApp.main(WebApp.java:13) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.4.0.jar:2.4.0]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.studerw.tda.demo.config.SpringDocConfig$$EnhancerBySpringCGLIB$$6e58deb6]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Required key 'api.prefix' not found
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:225) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.1.jar:5.3.1]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310) ~[spring-beans-5.3.1.jar:5.3.1]
        ... 25 common frames omitted
Caused by: java.lang.IllegalStateException: Required key 'api.prefix' not found
        at org.springframework.core.env.AbstractPropertyResolver.getRequiredProperty(AbstractPropertyResolver.java:183) ~[spring-core-5.3.1.jar:5.3.1]
        at org.springframework.core.env.AbstractEnvironment.getRequiredProperty(AbstractEnvironment.java:556) ~[spring-core-5.3.1.jar:5.3.1]
        at com.studerw.tda.demo.config.SpringDocConfig.<init>(SpringDocConfig.java:23) ~[classes/:na]
        at com.studerw.tda.demo.config.SpringDocConfig$$EnhancerBySpringCGLIB$$6e58deb6.<init>(<generated>) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212) ~[spring-beans-5.3.1.jar:5.3.1]
        ... 27 common frames omitted

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.658 s
[INFO] Finished at: 2021-08-25T01:36:45-05:00
[INFO] ------------------------------------------------------------------------

D:\samplecode\td-ameritrade-java-client-demo-master>

**Comment by studerw** [comment]
@ajaythukral  Sorry but I guess I didn't explain well in the README how to set the project up for running on command line or in IDE. Do a git pull of master and / or take a look at the README on the main project page here on Github to see the directions I just added.

Essentially, if you're running using `mvn spring-boot:run` or in Eclipse or IntelliJ, then you need to add the `application.properties` that are normally bundled with the app to the `src/main/resources` folder. That way the IDE or maven can use the properties, and then they'll be overridden by the external application.properties file that is bundled in the zip.

**Comment by ajaythukral** [comment]
Thanks for clarifications. After doing application. Properties changes , system was asking me to bring /config/tda-demo-server.jks . I i create a config folder and copied jks file into the same and after that web app started successfully. 


Still I am not able to access it through browser. It seems some certificate issue. I am sending server startup log for you attention
D:\samplecode\td-ameritrade-java-client-demo-master\target>java -jar td-ameritrade-java-client-demo-1.0.0.jar
It may be because of following error
**2021-08-25 18:54:47.259  WARN 1216 --- [           main] org.apache.tomcat.util.net.SSLUtilBase   : The trusted certificate with alias [tda-client-1] and DN [CN=tda-client-1, OU=TDA Demo Github, O=Unknown, L=Washington, ST=DC, C=US] is not valid due to [NotAfter: Tue Oct 27 22:25:11 CDT 2020]. Certificates signed by this trusted certificate WILL be accepted**

Any help on the same ?

**Comment by ajaythukral** [comment]
DETAIL OF STARTUP LOGS
D:\samplecode\td-ameritrade-java-client-demo-master\target>java -jar td-ameritrade-java-client-demo-1.0.0.jar
2021-08-25 18:54:42.416  INFO 1216 --- [           main] com.studerw.tda.demo.WebApp              : Starting WebApp v1.0.0 using Java 16.0.2 on DESKTOP-B7OGPA2 with PID 1216 (D:\samplecode\td-ameritrade-java-client-demo-master\target\td-ameritrade-java-client-demo-1.0.0.jar started by shvid in D:\samplecode\td-ameritrade-java-client-demo-master\target)
2021-08-25 18:54:42.421 DEBUG 1216 --- [           main] com.studerw.tda.demo.WebApp              : Running with Spring Boot v2.4.0, Spring v5.3.1
2021-08-25 18:54:42.423  INFO 1216 --- [           main] com.studerw.tda.demo.WebApp              : No active profile set, falling back to default profiles: default
2021-08-25 18:54:44.710  INFO 1216 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 443 (https)
2021-08-25 18:54:44.726  INFO 1216 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-08-25 18:54:44.727  INFO 1216 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.39]
2021-08-25 18:54:44.814  INFO 1216 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-08-25 18:54:44.814  INFO 1216 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2271 ms
2021-08-25 18:54:45.092  INFO 1216 --- [           main] c.s.tda.demo.config.ControllerSetup      : creating ControllerSetup -- should only see me once.
2021-08-25 18:54:45.095  INFO 1216 --- [           main] c.s.tda.demo.config.SpringDocConfig      : Instantiating SwaggerConfig - should only see me once
2021-08-25 18:54:45.096  INFO 1216 --- [           main] c.s.tda.demo.config.SpringDocConfig      : Using prefix: /api/v1 for Swagger
2021-08-25 18:54:45.284  INFO 1216 --- [           main] com.studerw.tda.demo.config.AppConfig    : Instantiating TdaClient - should only see me once
2021-08-25 18:54:45.293  INFO 1216 --- [           main] com.studerw.tda.client.HttpTdaClient     : Initiating HttpTdaClient...
2021-08-25 18:54:45.492  INFO 1216 --- [           main] com.studerw.tda.demo.tda.TdaController   : Instantiating TdaController - you should only see me once...
2021-08-25 18:54:45.590  INFO 1216 --- [           main] .s.s.UserDetailsServiceAutoConfiguration :

Using generated security password: #######

2021-08-25 18:54:45.710  INFO 1216 --- [           main] c.s.tda.demo.user.UserDetailsService     : Creating UserDetailsService - should only see me once
2021-08-25 18:54:45.787  INFO 1216 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@10567255, org.springframework.security.web.context.SecurityContextPersistenceFilter@1968a49c, org.springframework.security.web.header.HeaderWriterFilter@7bfc3126, org.springframework.security.web.authentication.logout.LogoutFilter@4102b1b1, org.springframework.security.web.authentication.preauth.x509.X509AuthenticationFilter@5fd9b663, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@19868320, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@3ef41c66, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@e362c57, org.springframework.security.web.session.SessionManagementFilter@78e16155, org.springframework.security.web.access.ExceptionTranslationFilter@2c282004, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@74a9c4b0]
2021-08-25 18:54:45.926  INFO 1216 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-08-25 18:54:46.286  INFO 1216 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
2021-08-25 18:54:47.144  INFO 1216 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 14 endpoint(s) beneath base path '/actuator'
2021-08-25 18:54:47.259  WARN 1216 --- [           main] org.apache.tomcat.util.net.SSLUtilBase   : The trusted certificate with alias [tda-client-1] and DN [CN=tda-client-1, OU=TDA Demo Github, O=Unknown, L=Washington, ST=DC, C=US] is not valid due to [NotAfter: Tue Oct 27 22:25:11 CDT 2020]. Certificates signed by this trusted certificate WILL be accepted
2021-08-25 18:54:47.292  INFO 1216 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 443 (https) with context path ''
2021-08-25 18:54:47.313  INFO 1216 --- [           main] com.studerw.tda.demo.WebApp              : Started WebApp in 5.626 seconds (JVM running for 6.33)
